version: "3"
services:
  camera:
    container_name: camera
    image: "frc4048-ros2"
    network_mode: host
    ipc: host
    privileged: true
    devices:
      - /dev/video0
    command: ["./start-arducam.sh"]
    restart: always
  inverse:
    container_name: inverse
    image: "frc4048-ros2"
    network_mode: host
    privileged: true
    ipc: host
    command: ["./start-inverse.sh"]
    restart: unless-stopped
  odometry:
    container_name: odometry
    image: "frc4048-ros2"
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - PUB_ROS=0
      - PUB_NT=1
    command: ["./start-odometry.sh"]
    restart: unless-stopped
  detection:
    container_name: detection
    image: "frc4048-ros2"
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - PUB_ROS=0
      - PUB_NT=1
    command: ["./start-detection.sh"]
    restart: unless-stopped
  lifesigns:
    container_name: lifesigns
    image: "frc4048-ros2"
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - PUB_ROS=0
      - PUB_NT=1
    command: ["./start-lifesigns.sh"]
    restart: unless-stopped
#  autoheal:
#    container_name: healer
#    image: "willfarrell/autoheal"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    environment:
#      - AUTOHEAL_INTERVAL=1
#    restart: always