version: "3"
services:
  monitor:
    container_name: ros-monitor
    image: frc4048-ros2
    network_mode: host
    ipc: host
    command: ["./start-monitor.sh"]
    restart: always
  camera:
    container_name: camera
    image: "frc4048-ros2"
    network_mode: host
    labels:
      - autoheal = true
    healthcheck:
      test: "'$(docker container inspect -f '{{.State.Running}}' ros-monitor )' = 'false'"
      interval: "0h0m1s"
      retries: 2
    ipc: host
    command: ["./start-logitech.sh"]
    restart: always
  inverse:
    container_name: inverse
    image: "frc4048-ros2"
    network_mode: host
    ipc: host
    command: ["./start-inverse.sh"]
    restart: unless-stopped
  odometry:
    container_name: odometry
    image: "frc4048-ros2"
    network_mode: host
    ipc: host
    environment:
      - PUB_ROS=0
      - PUB_NT=1
    command: ["./start-odometry.sh"]
    restart: unless-stopped
  autoheal:
    container_name: healer
    image: "willfarrell/autoheal"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - AUTOHEAL_INTERVAL=1
    restart: always